# https://github.com/crossplane-contrib/provider-upjet-azure/blob/main/examples/azure/user-assigned-managed-identity.yaml
# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0
apiVersion: v1
kind: Namespace
metadata:
  name: testapp02
---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: testapp02-umi ##ProviderConfig resources is not namespaced
spec:
  credentials:
    source: OIDCTokenFile
    # source: UserAssignedManagedIdentity
  oidcTokenFilePath: /var/run/secrets/azure/tokens/azure-identity-token
  clientID: 80589944-29c2-4f00-808f-b533b9986fb8
  subscriptionID: 841bc417-7db7-4e2e-82d3-c80bd04ab305
  tenantID: 613c9f59-45bd-41b1-8e2a-e7736e788431
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: testapp02
  annotations:
    crossplane.io/external-name: RG-WE-D-TESTAPP-02
spec:
  managementPolicies: ["Observe"]
  forProvider: {}
  providerConfigRef:
    name: testapp02-umi