apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: enable-ess
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: crossplain-azure-deploy
          containers:
            - name: package-runtime
              args:
                - --enable-external-secret-stores
                - --enable-management-policies