# https://github.com/crossplane-contrib/provider-upjet-azure/blob/main/examples/azure/user-assigned-managed-identity.yaml
# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0
apiVersion: v1
kind: Namespace
metadata:
  name: testapp01
---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: testapp01-umi ##ProviderConfig resources is not namespaced
spec:
  credentials:
    source: OIDCTokenFile
    # source: UserAssignedManagedIdentity
  oidcTokenFilePath: /var/run/secrets/azure/tokens/azure-identity-token
  clientID: #{clientID}#
  subscriptionID: #{subscriptionID}#
  tenantID: #{tenantID}#
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-we-d-testapp-01
  labels:
    app-name: testapp01
    resource-group-type: environment
    resource-group-environment: dev
  annotations:
    crossplane.io/external-name: #{resourceGroupId}#
spec:
  managementPolicies: ["Observe"]
  forProvider: {}
  providerConfigRef:
    name: testapp01-umi